color: lime
fieldLayouts:
  7abd8cbf-7923-41fd-aa12-25348b9de4a0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-09T19:10:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2e4bf258-13e4-4b97-bd30-2d60cf259fc4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-09T19:13:07+00:00'
            elementCondition: null
            fieldUid: 2111f3c3-64f4-4fc7-b472-16660716f927 # Simple Text
            handle: heading
            includeInCards: false
            instructions: null
            label: Heading
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 799e78be-3313-4126-bc8d-783d22406a6e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-09T19:13:07+00:00'
            elementCondition: null
            fieldUid: 2111f3c3-64f4-4fc7-b472-16660716f927 # Simple Text
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3b0047f-01f4-477a-84ab-abfbfe6e84b0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 275e287a-e0c2-4436-89d2-6123a081ac3c
        userCondition: null
handle: headingText
hasTitleField: true
icon: heading
name: Heading-Text
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
