color: lime
fieldLayouts:
  8a687e68-87f2-42f2-86ad-41305f9945be:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-09T19:53:34+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 33e9c29d-e626-4f77-a847-80c9095e34c7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-09T19:58:26+00:00'
            elementCondition: null
            fieldUid: 48af5fbc-7222-4fbb-a1b3-3580bde6cd8f # Image
            handle: cardImage
            includeInCards: false
            instructions: null
            label: 'Card Image'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28a8d6f0-da9c-4115-a62d-609f4c97e03a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-09T19:58:26+00:00'
            elementCondition: null
            fieldUid: 943728f2-6d55-4e4c-9e18-62e772182e54 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa2b3773-ec49-4806-8092-1c7a71471b46
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-09T19:58:26+00:00'
            elementCondition: null
            fieldUid: aef7941d-85db-4562-9531-f6d6fb4093a1 # Category Selector
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54a9ac46-5e98-401d-b170-e535318e03b7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 683c5679-0371-4c55-97aa-cb37a13fdd09
        userCondition: null
handle: imageCard
hasTitleField: true
icon: card-club
name: 'Image Card'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
