altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  4d81781f-8377-4a74-a638-85f8ce4b09fb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-09T20:58:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: e60dbdfe-36ba-42b7-a422-20db68e68ceb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 94873984-2b6d-43c6-8f60-8672fe7c0cb5
        userCondition: null
fs: media
handle: media
name: Media
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
