columnSuffix: null
handle: categorySelector
instructions: null
name: 'Category Selector'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  source: 'group:17afd6f9-d500-403e-b493-f285ff3967d7' # Projects Types
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
