columnSuffix: null
handle: contactLink
instructions: null
name: 'Contact Link'
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: true
  types:
    - email
    - tel
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
