columnSuffix: null
handle: iconField
instructions: null
name: 'Icon Field'
searchable: false
settings:
  includeProIcons: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Icon
