fieldLayouts:
  94c3cb77-b7cc-4f02-9388-f8c926b0a58c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-09T21:52:50+00:00'
            elementCondition: null
            fieldUid: 2111f3c3-64f4-4fc7-b472-16660716f927 # Simple Text
            handle: footerCopyright
            includeInCards: false
            instructions: null
            label: 'Footer Copyright'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e5a4d02-f601-4007-94df-738949b6e372
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7a1c6dea-d7e3-41f4-8128-d59294cb8e82
        userCondition: null
handle: footer
name: Footer
sortOrder: 2
