defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: b422501e-d0ab-420f-9286-dcffa1dd1e74 # Links
handle: navigation
maxAuthors: 1
name: Navigation
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  94f96324-ba1c-4e95-bce0-85caf50f9a97: # Quinten Claes
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 99189c04-f39b-422b-accb-caea45ca291b
type: structure
